name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - run: yarn --immutable

      - run: BASE_DIR=/catfactz/ yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
          SINGLE_COMMIT: true
